#!/usr/bin/env bash

# Function to send output from the commandline to Slack.
#
# @parameter string $MESSAGE Message to send to slack.
notifySlack ()
{
  if [ -z "$SLACK_WEBHOOK_URL" ]; then
    echo Please set SLACK_WEBHOOK_URL in your env.
    exit 1
  fi
  
  SLACK_CHANNEL=${SLACK_CHANNEL-'sandbox-group'};
  SLACK_BOTNAME=${SLACK_BOTNAME-$(hostname -s)};
  SLACK_BOTEMOJI=${SLACK_BOTEMOJI-':penguin:'}
  SLACK_ATTACHMENTS=${SLACK_ATTACHMENTS-'[]'}

  MESSAGE=$@;

  PAYLOAD="payload={\"channel\": \"${SLACK_CHANNEL}\", \"username\": \"${SLACK_BOTNAME}\", \"text\": \"${MESSAGE}\", \"icon_emoji\": \"${SLACK_BOTEMOJI}\", \"attachments\": ${SLACK_ATTACHMENTS}}";
  CURL_RESULT=$(curl -s -S -X POST --data-urlencode "$PAYLOAD" "${SLACK_WEBHOOK_URL}");

  if [ -z "$CURL_RESULT" ] || [ "$CURL_RESULT" = "ok" ]; then
    return 0;
  else
    echo "Slack error: ${CURL_RESULT}"
    echo "payload: ${PAYLOAD}"
    return 1;
  fi
}

